### ISSUE TITLE
PGR 4 Support

### ISSUE THREAD

**Issue by MrTegs** [bartek360/BizarreResearch#1]
can you please make an animation, mesh and texture extractor for PGR4? 
I'm willing to pay. i've been able to extract the raw files from the xbox 360 iso and pak. 
Although the files end in .ska, .skm, and .ctx. i believe they are the three formats i mentioned above.

**Comment by bartek360** [comment]
Thank you for the offer but not planned.
Bizarre's formats from PGR3 onward were heavily retooled (instead of derived from MSR) and tackled by other researchers.

**Comment by MrTegs** [comment]
> Thank you for the offer but not planned. Bizarre's formats from PGR3 onward were heavily retooled (instead of derived from MSR) and tackled by other researchers.

Thanks for letting me know. BTW can you help delete this issue. I want to. But i can't
